/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marionettesim.gui.tabs;

import javax.swing.JTextField;
import marionettesim.gui.MainForm;
import marionettesim.math.Vector3f;
import marionettesim.simulation.Simulation;
import marionettesim.utils.Parse;
import marionettesim.utils.StringUtils;

/**
 *
 * @author Asier
 */
public class HandPanel extends javax.swing.JPanel {
    MainForm mf;
    
    
    
    public HandPanel(MainForm mf) {
        this.mf = mf;
        initComponents();
        objectsToGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1XText = new javax.swing.JTextField();
        f1ZText = new javax.swing.JTextField();
        f1RyText = new javax.swing.JTextField();
        f2RyText = new javax.swing.JTextField();
        f2XText = new javax.swing.JTextField();
        f2ZText = new javax.swing.JTextField();
        f3RyText = new javax.swing.JTextField();
        f3XText = new javax.swing.JTextField();
        f3ZText = new javax.swing.JTextField();
        f4RyText = new javax.swing.JTextField();
        f4XText = new javax.swing.JTextField();
        f4ZText = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();

        f1XText.setText("F1 X");

        f1ZText.setText("F1 Z");

        f1RyText.setText("F1 RY");

        f2RyText.setText("F2 RY");

        f2XText.setText("F2 X");

        f2ZText.setText("F2 Z");

        f3RyText.setText("F3 RY");

        f3XText.setText("F3 X");

        f3ZText.setText("F3 Z");

        f4RyText.setText("F4 RY");

        f4XText.setText("F4 X");

        f4ZText.setText("F4 Z");

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f1RyText)
                            .addComponent(f1XText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f1ZText))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f2RyText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(f2XText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f2ZText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f3RyText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(f3XText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f3ZText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f4RyText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(f4XText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f4ZText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1XText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f1ZText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f1RyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2XText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2ZText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f2RyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f3XText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f3ZText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f3RyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f4XText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f4ZText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f4RyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applyButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        guiToObjects();
        mf.needUpdate();
    }//GEN-LAST:event_applyButtonActionPerformed

    
    private void guiToObjects(){
        final Vector3f[] f = mf.simulation.getFingersOffsets();
        guiToObject(f1XText, f1ZText, f1RyText, f[0]);
        guiToObject(f2XText, f2ZText, f2RyText, f[1]);
        guiToObject(f3XText, f3ZText, f3RyText, f[2]);
        guiToObject(f4XText, f4ZText, f4RyText, f[3]);
    }

    private void objectsToGUI(){
        final Vector3f[] f = mf.simulation.getFingersOffsets();
        objectToGUI(f1XText, f1ZText, f1RyText, f[0]);
        objectToGUI(f2XText, f2ZText, f2RyText, f[1]);
        objectToGUI(f3XText, f3ZText, f3RyText, f[2]);
        objectToGUI(f4XText, f4ZText, f4RyText, f[3]);
    }

    private static void guiToObject(JTextField tx, JTextField tz, JTextField tRy, Vector3f v){
        v.x = Parse.stringToFloat( tx.getText() );
        v.y = Parse.stringToFloat( tRy.getText() );
        v.z = Parse.stringToFloat( tz.getText() );
    }
    
    private static void objectToGUI(JTextField tx, JTextField tz, JTextField tRy, Vector3f v){
        tx.setText( StringUtils.get().fourDecs( v.x ) );
        tz.setText( StringUtils.get().fourDecs( v.z ) );
        tRy.setText( StringUtils.get().fourDecs( v.y ) );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JTextField f1RyText;
    private javax.swing.JTextField f1XText;
    private javax.swing.JTextField f1ZText;
    private javax.swing.JTextField f2RyText;
    private javax.swing.JTextField f2XText;
    private javax.swing.JTextField f2ZText;
    private javax.swing.JTextField f3RyText;
    private javax.swing.JTextField f3XText;
    private javax.swing.JTextField f3ZText;
    private javax.swing.JTextField f4RyText;
    private javax.swing.JTextField f4XText;
    private javax.swing.JTextField f4ZText;
    // End of variables declaration//GEN-END:variables
}
