/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marionettesim.gui.tabs;

import marionettesim.gui.MainForm;
import marionettesim.math.Vector3f;
import marionettesim.scene.Entity;
import marionettesim.scene.Scene;
import marionettesim.simulation.EntityTag;
import marionettesim.utils.Parse;
import marionettesim.utils.StringUtils;

/**
 *
 * @author Asier
 */
public class SimPanel extends javax.swing.JPanel {
    public MainForm mf;
    
    public SimPanel(MainForm mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        minXText = new javax.swing.JTextField();
        maxXText = new javax.swing.JTextField();
        minYText = new javax.swing.JTextField();
        maxYText = new javax.swing.JTextField();
        minZText = new javax.swing.JTextField();
        maxZText = new javax.swing.JTextField();
        applySizeButton = new javax.swing.JButton();
        autoSizeButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        guiGainText = new javax.swing.JTextField();
        showSimBBCheck = new javax.swing.JCheckBox();

        jLabel18.setText("Sim Size");

        minXText.setText("minX");

        maxXText.setText("maxX");

        minYText.setText("minY");

        maxYText.setText("maxY");

        minZText.setText("minZ");

        maxZText.setText("maxZ");

        applySizeButton.setText("Apply");
        applySizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applySizeButtonActionPerformed(evt);
            }
        });

        autoSizeButton.setText("Auto");
        autoSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoSizeButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("GUI gain");

        guiGainText.setText("0.01");

        showSimBBCheck.setSelected(true);
        showSimBBCheck.setText("ShowBB");
        showSimBBCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSimBBCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showSimBBCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(minYText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minXText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minZText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxYText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxXText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxZText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guiGainText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applySizeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autoSizeButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(guiGainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(applySizeButton)
                    .addComponent(autoSizeButton))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minZText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxZText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showSimBBCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applySizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applySizeButtonActionPerformed
        guiToSimulationBoundaries();
        mf.simulation.updateBoundaryBoxes();
        mf.needUpdate();
    }//GEN-LAST:event_applySizeButtonActionPerformed

    private void autoSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoSizeButtonActionPerformed
        mf.simulation.updateBoundaryBoxes();
        mf.scene.adjustCameraNearAndFar(mf.simulation);
        simulationBoundariesToGUI();
        mf.needUpdate();
    }//GEN-LAST:event_autoSizeButtonActionPerformed

    private void showSimBBCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSimBBCheckActionPerformed
        Scene.setVisible(mf.scene.getEntities(), EntityTag.SIMULATION_BOUNDINGS, showSimBBCheck.isSelected());
        mf.needUpdate();
    }//GEN-LAST:event_showSimBBCheckActionPerformed

    public float getGUIGain(){
        return Parse.stringToFloat( guiGainText.getText() );
    }
    
    public void guiToSimulationBoundaries(){
        Vector3f max = mf.simulation.getBoundaryMax();
        Vector3f min = mf.simulation.getBoundaryMin();
        min.x = Parse.stringToFloat( minXText.getText() );
        min.y = Parse.stringToFloat( minYText.getText() );
        min.z = Parse.stringToFloat( minZText.getText() );
        max.x = Parse.stringToFloat( maxXText.getText() );
        max.y = Parse.stringToFloat( maxYText.getText() );
        max.z = Parse.stringToFloat( maxZText.getText() );
        mf.simulation.updateBoundaryBoxes();
    }
    
    public void simulationBoundariesToGUI(){
        Vector3f max = mf.simulation.getBoundaryMax();
        Vector3f min = mf.simulation.getBoundaryMin();
        minXText.setText( StringUtils.get().fourDecs( min.x ));
        minYText.setText( StringUtils.get().fourDecs( min.y ));
        minZText.setText( StringUtils.get().fourDecs( min.z ));
        maxXText.setText( StringUtils.get().fourDecs( max.x ));
        maxYText.setText( StringUtils.get().fourDecs( max.y ));
        maxZText.setText( StringUtils.get().fourDecs( max.z ));
        guiGainText.setText( StringUtils.get().fourDecs( mf.simulation.minDistanceBoundary() / 100.0f));
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applySizeButton;
    private javax.swing.JButton autoSizeButton;
    private javax.swing.JTextField guiGainText;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JTextField maxXText;
    private javax.swing.JTextField maxYText;
    private javax.swing.JTextField maxZText;
    private javax.swing.JTextField minXText;
    private javax.swing.JTextField minYText;
    private javax.swing.JTextField minZText;
    private javax.swing.JCheckBox showSimBBCheck;
    // End of variables declaration//GEN-END:variables
}
