/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marionettesim.gui.tabs;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import marionettesim.gui.MainForm;
import marionettesim.gui.controls.ScriptEditFrame;
import marionettesim.scene.MeshEntity;
import marionettesim.scene.Resources;
import marionettesim.shapes.Quad;
import marionettesim.simulation.Function2D;
import marionettesim.simulation.functions.CurvatureFunction;
import marionettesim.simulation.functions.HapticImage;
import marionettesim.utils.FileUtils;
import marionettesim.utils.Parse;
import marionettesim.workers.KinectWorker;
import marionettesim.workers.PlayerThread;

/**
 *
 * @author Asier
 */
public class SurfacePanel extends javax.swing.JPanel {
    public MainForm mf;
    private final PlayerThread player;
    private final ScriptEditFrame scriptFrame;
    private final KinectWorker kinectWorker;
    
    public SurfacePanel(MainForm mf) {
        this.mf = mf;
        
        initComponents();
        scriptFrame = new ScriptEditFrame(mf);
        player = new PlayerThread(this);
        player.start();
        
        kinectWorker = new KinectWorker(mf);
        kinectWorker.start();
    }

    public float getGain(){
        return Parse.stringToFloat( gainText.getText() );
    }
    public float getMinColor(){
        return Parse.stringToFloat( colAmpMinText.getText() );
    }
    public float getMaxColor(){
        return Parse.stringToFloat( colAmpMaxText.getText() );
    }
    public int getColorGradient(){
        return colouringCombo.getSelectedIndex();
    }
    public boolean isPlaying(){
        return enableDinamicCheck.isSelected();
    }
    public float getFPS(){
        return Parse.stringToFloat( fpsText.getText() );
    }
    
    
    public String getGlslScript() {
        return scriptFrame.getGlslScript();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sizeXText = new javax.swing.JTextField();
        sizeYText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gridDivsText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        gainText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        curvatureText = new javax.swing.JTextField();
        applyCurvatureButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();
        selectFileText = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        resizeText = new javax.swing.JTextField();
        imageApplyButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        editScriptsButton = new javax.swing.JButton();
        enableDinamicCheck = new javax.swing.JCheckBox();
        fpsText = new javax.swing.JTextField();
        resetTimeButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        kinectCheck = new javax.swing.JCheckBox();
        kinectFPSText = new javax.swing.JTextField();
        createKinectFunctionButton = new javax.swing.JButton();
        kinectRepaintCheck = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        kinectStartXText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kinectStartYText = new javax.swing.JTextField();
        kinectApplyButton = new javax.swing.JButton();
        snapKinectBackgroundButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        kinectMaxDiffText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kinectFilterText = new javax.swing.JTextField();
        colouringCombo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        colAmpMinText = new javax.swing.JTextField();
        colAmpMaxText = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel1.setText("Size");

        sizeXText.setText("0.2");
        sizeXText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeXTextActionPerformed(evt);
            }
        });

        sizeYText.setText("0.2");
        sizeYText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeYTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Grid divs:");

        gridDivsText.setText("128");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Gain:");

        gainText.setText("1.0");
        gainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Color:");

        jLabel5.setText("curvature:");

        curvatureText.setText("2");

        applyCurvatureButton.setText("Apply");
        applyCurvatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyCurvatureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curvatureText, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(applyCurvatureButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(curvatureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyCurvatureButton)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Curvature", jPanel1);

        jLabel6.setText("path:");

        selectFileText.setText("Select");
        selectFileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileTextActionPerformed(evt);
            }
        });

        jLabel7.setText("resize to:");

        resizeText.setText("128");

        imageApplyButton.setText("Apply");
        imageApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageApplyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathText, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFileText))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resizeText))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imageApplyButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(resizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(imageApplyButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Image", jPanel2);

        editScriptsButton.setText("Edit scripts");
        editScriptsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editScriptsButtonActionPerformed(evt);
            }
        });

        enableDinamicCheck.setText("enable");
        enableDinamicCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableDinamicCheckActionPerformed(evt);
            }
        });

        fpsText.setText("30");

        resetTimeButton.setText("reset time");
        resetTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTimeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(editScriptsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(resetTimeButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(enableDinamicCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fpsText)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableDinamicCheck)
                    .addComponent(fpsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editScriptsButton)
                    .addComponent(resetTimeButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("JS+GLSL", jPanel3);

        kinectCheck.setText("enable");
        kinectCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinectCheckActionPerformed(evt);
            }
        });

        kinectFPSText.setText("30");

        createKinectFunctionButton.setText("Create");
        createKinectFunctionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createKinectFunctionButtonActionPerformed(evt);
            }
        });

        kinectRepaintCheck.setText("repaint");

        jLabel8.setText("Xstart:");

        kinectStartXText.setText("96");

        jLabel9.setText("Ystart:");

        kinectStartYText.setText("56");

        kinectApplyButton.setText("Apply");
        kinectApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinectApplyButtonActionPerformed(evt);
            }
        });

        snapKinectBackgroundButton.setText("Snap background");
        snapKinectBackgroundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapKinectBackgroundButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("maxDiff:");

        kinectMaxDiffText.setText("1000");

        jLabel12.setText("filter:");

        kinectFilterText.setText("0.8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(kinectCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kinectFPSText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kinectRepaintCheck))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(createKinectFunctionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(snapKinectBackgroundButton))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kinectApplyButton)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kinectMaxDiffText))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kinectStartXText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kinectStartYText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kinectFilterText))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kinectCheck)
                    .addComponent(kinectFPSText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kinectRepaintCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createKinectFunctionButton)
                    .addComponent(snapKinectBackgroundButton))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kinectMaxDiffText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(kinectFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kinectStartXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(kinectStartYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kinectApplyButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kinect", jPanel4);

        colouringCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "fire", "hue", "brown to blue", "test1", " " }));
        colouringCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colouringComboActionPerformed(evt);
            }
        });

        jLabel11.setText("AmpCol:");

        colAmpMinText.setText("0");
        colAmpMinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colAmpMinTextActionPerformed(evt);
            }
        });

        colAmpMaxText.setText("0.05");
        colAmpMaxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colAmpMaxTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeXText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeYText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gridDivsText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gainText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colouringCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colAmpMinText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colAmpMaxText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {colAmpMaxText, colAmpMinText});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sizeXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gridDivsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(colouringCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(colAmpMinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colAmpMaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colouringComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colouringComboActionPerformed
        mf.needUpdate();
    }//GEN-LAST:event_colouringComboActionPerformed

    private void colAmpMinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colAmpMinTextActionPerformed
        mf.needUpdate();
    }//GEN-LAST:event_colAmpMinTextActionPerformed

    private void colAmpMaxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colAmpMaxTextActionPerformed
        mf.needUpdate();
    }//GEN-LAST:event_colAmpMaxTextActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        final int divs = Parse.stringToInt( gridDivsText.getText() );
        final MeshEntity surface = mf.simulation.getSurface();
        
        surface.customMesh = new Quad(1.0f, 1.0f, divs);
        surface.setMesh( Resources.MESH_CUSTOM );
        
        mf.needUpdate();
    }//GEN-LAST:event_okButtonActionPerformed

    private void updateSurfaceSize(){
        final float sx = Parse.stringToFloat( sizeXText.getText() );
        final float sy = Parse.stringToFloat( sizeYText.getText() );
        
        final MeshEntity surface = mf.simulation.getSurface();
        surface.getTransform().getScale().set(sx, sy, 1.0f);
        
        mf.needUpdate();
    }
    
    private void sizeXTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeXTextActionPerformed
        updateSurfaceSize();
    }//GEN-LAST:event_sizeXTextActionPerformed

    private void sizeYTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeYTextActionPerformed
       updateSurfaceSize();
    }//GEN-LAST:event_sizeYTextActionPerformed

    private void imageApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageApplyButtonActionPerformed
        final String path = pathText.getText();
        final int size = Parse.stringToInt( resizeText.getText() );
        final float w = mf.simulation.getSurfaceWidth();
        final float h = mf.simulation.getSurfaceHeight();
        final float gain = getGain();

        HapticImage image = new HapticImage(path, w, h);
        try {
            final float topHeight = mf.simulation.getBoundaryMax().y;
            image.loadImage(size, topHeight);
            mf.simulation.applyNewFunction(image, gain);
            mf.needUpdate();
        } catch (IOException ex) {
            Logger.getLogger(SurfacePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_imageApplyButtonActionPerformed

    private void selectFileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileTextActionPerformed
        String path = FileUtils.selectFile(this, "open", "", null);
        if(path != null){
            pathText.setText(path);
        }
    }//GEN-LAST:event_selectFileTextActionPerformed

    private void applyCurvatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyCurvatureButtonActionPerformed
        final float gain = getGain();
        final float curvature = Parse.stringToFloat( curvatureText.getText() );
        final float width = mf.simulation.getSurfaceWidth();

        Function2D f = new CurvatureFunction(curvature, width);
        mf.simulation.applyNewFunction(f, gain);

        mf.needUpdate();
    }//GEN-LAST:event_applyCurvatureButtonActionPerformed

    private void enableDinamicCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableDinamicCheckActionPerformed
        player.playOrPause();
    }//GEN-LAST:event_enableDinamicCheckActionPerformed

    private void editScriptsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editScriptsButtonActionPerformed
        scriptFrame.setVisible(true);
    }//GEN-LAST:event_editScriptsButtonActionPerformed

    private void resetTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTimeButtonActionPerformed
        mf.simulation.resetTime();
    }//GEN-LAST:event_resetTimeButtonActionPerformed

    public boolean isKinectEnabled(){
        return kinectCheck.isSelected();
    }
    
    public boolean isKinectRepaint(){
        return kinectRepaintCheck.isSelected();
    }
    
    public float getKinectFrames(){
        return Parse.stringToFloat( kinectFPSText.getText() );
    }

    public int getKinectX(){
        return Parse.stringToInt( kinectStartXText.getText() );
    }
    
    public int getKinectY(){
        return Parse.stringToInt( kinectStartYText.getText() );
    }
    
    private void gainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gainTextActionPerformed

    private void kinectCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinectCheckActionPerformed
        kinectWorker.wakeUp();
    }//GEN-LAST:event_kinectCheckActionPerformed

    private void kinectApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinectApplyButtonActionPerformed
        mf.simulation.applyNewFunction(kinectWorker.getFunction(), mf.surfacePanel.getGain());
    }//GEN-LAST:event_kinectApplyButtonActionPerformed

    private void createKinectFunctionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createKinectFunctionButtonActionPerformed
        kinectWorker.createFunction();
    }//GEN-LAST:event_createKinectFunctionButtonActionPerformed

    private void snapKinectBackgroundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapKinectBackgroundButtonActionPerformed
        kinectWorker.snapFunctionBackground(); 
    }//GEN-LAST:event_snapKinectBackgroundButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyCurvatureButton;
    private javax.swing.JTextField colAmpMaxText;
    private javax.swing.JTextField colAmpMinText;
    private javax.swing.JComboBox colouringCombo;
    private javax.swing.JButton createKinectFunctionButton;
    private javax.swing.JTextField curvatureText;
    private javax.swing.JButton editScriptsButton;
    private javax.swing.JCheckBox enableDinamicCheck;
    private javax.swing.JTextField fpsText;
    private javax.swing.JTextField gainText;
    private javax.swing.JTextField gridDivsText;
    private javax.swing.JButton imageApplyButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kinectApplyButton;
    private javax.swing.JCheckBox kinectCheck;
    private javax.swing.JTextField kinectFPSText;
    private javax.swing.JTextField kinectFilterText;
    private javax.swing.JTextField kinectMaxDiffText;
    private javax.swing.JCheckBox kinectRepaintCheck;
    private javax.swing.JTextField kinectStartXText;
    private javax.swing.JTextField kinectStartYText;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField pathText;
    private javax.swing.JButton resetTimeButton;
    private javax.swing.JTextField resizeText;
    private javax.swing.JButton selectFileText;
    private javax.swing.JTextField sizeXText;
    private javax.swing.JTextField sizeYText;
    private javax.swing.JButton snapKinectBackgroundButton;
    // End of variables declaration//GEN-END:variables

    public float getKinectMaxDiff() {
        return Parse.stringToFloat( kinectMaxDiffText.getText() );
    }

    public float getKinectFilter(){
        return Parse.stringToFloat( kinectFilterText.getText() );
    }
    

    
}
