/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marionettesim.gui;

import marionettesim.workers.KinectWorker;
import marionettesim.scene.Scene;
import marionettesim.utils.Parse;

/**
 *
 * @author Asier
 */
public class KinectControlForm extends javax.swing.JFrame {
    MainForm form;
    Scene scene;
    KinectWorker worker;

    public KinectWorker getWorker() {
        return worker;
    }
    
    
    public KinectControlForm(MainForm form, Scene renderer) {
        this.form = form;
        this.scene = renderer;
        initComponents();
        
        worker = new KinectWorker(form, this);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enabledCheck = new javax.swing.JCheckBox();
        repaintCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        stepsText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        minDepthText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxDepthText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        latencyText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        szText = new javax.swing.JTextField();
        transformButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kinect Mesh");

        enabledCheck.setText("Enable");
        enabledCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledCheckActionPerformed(evt);
            }
        });

        repaintCheck.setText("repaint");

        jLabel1.setText("Step:");

        stepsText.setText("8");

        jLabel2.setText("MinDepth:");

        minDepthText.setText("500");

        jLabel3.setText("MaxDepth:");

        maxDepthText.setText("1000");

        jLabel4.setText("Latency:");

        latencyText.setText("30");

        jLabel5.setText("SustractZ:");

        szText.setText("500");

        transformButon.setText("Edit Transform");
        transformButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enabledCheck)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepsText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(latencyText))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(szText))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minDepthText, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxDepthText)
                            .addComponent(repaintCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transformButon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enabledCheck)
                    .addComponent(jLabel1)
                    .addComponent(stepsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(latencyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(minDepthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(maxDepthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(szText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repaintCheck))
                .addGap(18, 18, 18)
                .addComponent(transformButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transformButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformButonActionPerformed
        TransformForm.editTransform( form.simulation.getKinectSlice().getTransform() , this);
    }//GEN-LAST:event_transformButonActionPerformed

    private void enabledCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledCheckActionPerformed
        if (enabledCheck.isSelected() && !worker.isAlive()){
            worker.start();
        }
        
        worker.wakeUp();
        form.simulation.getKinectSlice().setVisible( enabledCheck.isSelected() );
    }//GEN-LAST:event_enabledCheckActionPerformed

    public boolean isKinectEnabled(){
        return enabledCheck.isSelected();
    }
    
    public int getSteps(){
        return Parse.stringToInt(stepsText.getText() );
    }
    
    public float getLatency(){
        return Parse.stringToFloat(latencyText.getText() );
    }
    
    public float getMinDepth(){
        return Parse.stringToFloat( minDepthText.getText() );
    }
    
    public float getMaxDepth(){
        return Parse.stringToFloat( maxDepthText.getText() );
    }

    public float getSustractZ(){
        return Parse.stringToFloat( szText.getText() );
    }
    
    public boolean isRepaint(){
        return repaintCheck.isSelected();
    }

    public MainForm getForm() {
        return form;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox enabledCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField latencyText;
    private javax.swing.JTextField maxDepthText;
    private javax.swing.JTextField minDepthText;
    private javax.swing.JCheckBox repaintCheck;
    private javax.swing.JTextField stepsText;
    private javax.swing.JTextField szText;
    private javax.swing.JButton transformButon;
    // End of variables declaration//GEN-END:variables
}
