/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marionettesim.gui;

import marionettesim.workers.UdpControlWorker;

/**
 *
 * @author Asier
 */
public class UDPControlForm extends javax.swing.JFrame {
    MainForm mf;
    UdpControlWorker worker;
    
    public UDPControlForm(MainForm mf) {
        this.mf = mf;
        initComponents();
        
        worker = new UdpControlWorker(this, mf.getSimulation());
    }
    
    public int getPort(){
        return Integer.parseInt( portText.getText() );
    }
    
    public boolean isCheckEnabled(){
        return enableCheck.isSelected();
    }
    
    public boolean isRepaint(){
        return repaintCheck.isSelected();
    }
    

    public MainForm getMf() {
        return mf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enableCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        portText = new javax.swing.JTextField();
        repaintCheck = new javax.swing.JCheckBox();

        setTitle("UDP remote control");

        enableCheck.setText("enable");
        enableCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableCheckActionPerformed(evt);
            }
        });

        jLabel1.setText("port:");

        portText.setText("45816");

        repaintCheck.setText("repaint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(repaintCheck)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enableCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableCheck)
                    .addComponent(jLabel1)
                    .addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repaintCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enableCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableCheckActionPerformed
        if (enableCheck.isSelected() && !worker.isAlive()){
            worker.start();
        }
    }//GEN-LAST:event_enableCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox enableCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField portText;
    private javax.swing.JCheckBox repaintCheck;
    // End of variables declaration//GEN-END:variables
}
